services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - upload:/rails/storage
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3030:3000"
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_HOST: db
      DB_USER: ${DATABASE_USER}
      DB_PASS: ${DATABASE_PASSWORD}

volumes:
  db_data:
  upload: