#!/bin/bash
set -e

mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};
    CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME}_test;
    CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME}_production;
    CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME}_cache;
    CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME}_queue;
    CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME}_cable;
    GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'%';
    GRANT ALL PRIVILEGES ON ${DATABASE_NAME}_test.* TO '${DATABASE_USER}'@'%';
    GRANT ALL PRIVILEGES ON ${DATABASE_NAME}_production.* TO '${DATABASE_USER}'@'%';
    GRANT ALL PRIVILEGES ON ${DATABASE_NAME}_production_cache.* TO '${DATABASE_USER}'@'%';
    GRANT ALL PRIVILEGES ON ${DATABASE_NAME}_production_queue.* TO '${DATABASE_USER}'@'%';
    GRANT ALL PRIVILEGES ON ${DATABASE_NAME}_production_cable.* TO '${DATABASE_USER}'@'%';
EOSQL
